# Generated by Django 5.0.4 on 2024-05-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_item_image_news_item_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_item',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
