# Generated by Django 5.0.4 on 2024-05-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_about_company_faq_promocode_review_vacancy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='definition',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='term',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='news_item',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
