# Generated by Django 5.0.4 on 2024-05-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_manufacturer_producttype_order_product_orderproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='main.orderProduct', to='main.product'),
        ),
    ]
