# Generated by Django 5.0.4 on 2024-05-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_manufacturer_city_contact_alter_order_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_company',
            options={'verbose_name': 'О компании', 'verbose_name_plural': 'О компании'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Вопрос-ответ', 'verbose_name_plural': 'Вопросы-ответы'},
        ),
        migrations.AlterModelOptions(
            name='news_item',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промокод и купон', 'verbose_name_plural': 'Промокоды и купоны'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='employees/employee.jpg', upload_to='employees'),
        ),
    ]
