# Generated by Django 5.0.4 on 2024-05-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='birth_date',
            new_name='date_of_birth',
        ),
    ]
