# Generated by Django 5.0.4 on 2024-05-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_birth_date_client_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='birth_date',
            new_name='date_of_birth',
        ),
    ]
