# Generated by Django 5.0.4 on 2024-05-10 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 10)),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='yanakv@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='+375291234567', max_length=13),
        ),
    ]
