# Generated by Django 5.0.4 on 2024-05-11 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_employee_date_remove_employee_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Изготовитель', 'verbose_name_plural': 'Изготовители'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Вид товаров', 'verbose_name_plural': 'Виды товаров'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='contact',
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='city',
            field=models.CharField(default='Минск', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client'),
        ),
    ]
