# Generated by Django 5.0.4 on 2024-05-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_manufacturer_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='email@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='+375291234567', max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(default='2004-12-12'),
        ),
    ]
