# Generated by Django 5.0.4 on 2024-05-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_client_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(default='2004-12-12'),
        ),
    ]
