# Generated by Django 5.0.4 on 2024-05-11 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_client_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date_of_birth',
        ),
    ]
