# Generated by Django 5.0.4 on 2024-05-11 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_employee_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date_of_birth',
        ),
    ]
