# Generated by Django 5.0.4 on 2024-05-11 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_employee_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
