# Generated by Django 5.0.4 on 2024-05-11 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
