# Generated by Django 5.0.4 on 2024-05-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_orderproduct_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='pickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('working_hours', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Точка самовывоза',
                'verbose_name_plural': 'Точки самовывоза',
            },
        ),
    ]
