# Generated by Django 5.0.4 on 2024-05-11 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_pickuppoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuppoint',
            name='name',
        ),
    ]
