# Generated by Django 5.0.4 on 2024-05-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_remove_pickuppoint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(default='Минск', max_length=100),
        ),
    ]
