# Generated by Django 5.0.4 on 2024-05-21 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_client_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды и купоны'},
        ),
        migrations.AddField(
            model_name='promocode',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),

    ]
