# Generated by Django 5.0.4 on 2024-05-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_promocode_options_promocode_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='number_of_percents',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
