# Generated by Django 5.0.4 on 2024-05-21 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_promocode_number_of_percents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='number_of_percents',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
